G-Node/gin-doi

- Dockerfile
- cmd/gindoid/dstorage.go
- cmd/gindoid/mailserver.go
- cmd/gindoid/main.go
Instead of setting a single email address on the command line, the
service now accepts a filepath that should contain a list of email
address (one per line). Whenever a request is received, the notification
is sent to all email addresses listed in the file.
The message has also been changed to add the From and To addresses into
the email message header and not just specified through the SMTP
commands. This puts all the recipient addresses in the email To: line,
instead of BCCing the recipients.
The file is read every time a message is about to be sent, so the
recipients can be changed without restarting the service.
> Support multiple email recipients for notification

- cmd/gindoid/auth.go
- cmd/gindoid/datasource.go
- cmd/gindoid/dstorage.go
- cmd/gindoid/gindoi.go
- cmd/gindoid/main.go
- cmd/gindoid/util.go
- Working towards removing internal and old (gin) types for user information and instead using gogs structs (gogs.User).  This sets off changes all over the repository.
- Send an encrypted string that includes the username and repository (the same info in the URL query) for verification.  This is to verify that the request comes from our GIN server.
GOGS counterpart: https://github.com/G-Node/gogs/commit/19ee3ece22b86950fa27db4cbdce41bb877f96bf
> GOGS user info struct and new verification method

- cmd/gindoid/dstorage.go
The clone directory is always created based on the reponame but in all
lowercase.  The zip creation would fail if there were uppercase
characters in the name.  Lowercasing the path for cleanup (annex uninit
and .git removal) and zip creation too.
Fixes #17
> Use lowercase name for repo path when zipping

- .travis.yml
- cmd/gindoid/datasource.go
If there's no colon in the string, idparts[] indexing would cause an error.  If there's no colon, just return an empty string for the URL.
> Fix for parsing malformed reference IDs

- cmd/gindoid/dstorage.go
- cmd/gindoid/util.go
Sending the notification email before beginning the archive job is good for a couple of reasons:
- We get the notification as soon as the service knows it's valid and it doesn't have to wait for a long running job to complete.  Archive jobs can take a very long time if the repository is big (hundreds of GiB).
- If a repository causes issues (extremely large repository, an uncaught error in the archiving process, etc) that put the service in a faulty state, one which prevents sending emails, the request isn't lost.
One downside is that if any issues occur during archiving, we no longer get them in the notification email.  This is currently remedied by resending the email with error messages attached when needed.
> Send email early (before starting archive job)

- cmd/gindoid/assetserver.go
- cmd/gindoid/dstorage.go
- cmd/gindoid/main.go
Using the relative path `./assets` broke asset loading when the service working directory was anywhere else, which happened cloning and zipping archives.
This PR additionally blocks directory listings in the asset directory.  Keeping it isn't an issue, but it's not a bad idea to disallow them.
> Fix static asset loading during clone

- cmd/gindoid/dataset.go
- cmd/gindoid/mail.go
- cmd/gindoid/reginfo.go
- cmd/gindoid/templates.go
- cmd/gindoid/web.go
The main purpose of this PR is changing the storage directory of the registered datasets to use the DOI instead of a UUID.  Using the DOI instead of the UUID makes for nicer (and predictable)
landing page URLs.  The dataset landing pages will now be in the form `https://doid.gin.g-node.org/<DOI>`.
This also changes the zip filename to use the name of the original repository.  Using the DOI would be an issue since it contains a slash `/`.  The UUID could still be used but isn't as nice.  The repository name is (theoretically) meaningful and is also guaranteed to be a valid filename.
The PR also includes some refactoring of the DOI metadata file parsing functions.
> DOI-based dataset directory

- cmd/gindoid/main.go
- cmd/gindoid/templates.go
- cmd/gindoid/web.go
This PR redesigns the way the submission page and response to the submission works.
- Previously, the Request DOI Now button was handled by an embedded javascript function that called the 'do/' route on the service, received a response (success or error) and a message and displayed the message.  Now the route (renamed to `submit/`) renders a response using a new template.
- Email failures: If the notification email sending fails (misconfigured mail server address, or the mail server is down), the user will be instructed to contact us.
- Template failures: If the response template fails to be parsed (which shouldn't happen, since we now embed the templates in code), the message will be rendered in plain `<html>...</html>` tags, so the message is not lost.
Note: Whenever I change a log …
> Request result page redesign

- cmd/gindoid/dataset.go
- cmd/gindoid/reginfo.go
- cmd/gindoid/templates.go
Landing page was still being rendered linking to old zip file format (UUID).  cloneAndZip() function now returns filename (with .zip extension) for the created archive, which gets added to the DOIInfo struct, and the template uses it in the template.
> Fix: ZIP file link in landing page template

- cmd/gindoid/dataset.go
Replacing the / with _ instead of - for the DOI that's transformed to a safe filename.
Requested by Thomas.
> Use underscore instead of dash in zip filename

- cmd/gindoid/reginfo.go
- cmd/gindoid/templates.go
- cmd/gindoid/util.go
The datacite.yml template requests funding references to separate funder name from award number with a comma.  When rendering the XML file, we can split on comma to populate the funding field more completely.
If there are no commas, the complete reference is returned only for the funder name field, like we did before this change.
> Funding ref split

- templates/reqpage.go
Changes to the DOI preparation (preview) page based on comments from Thomas.
See image below for a sample of what the new page looks like.
> Prep page changes

- cmd/gindoid/genhtml.go
- cmd/gindoid/web.go
DOIs are now randomly generated until a new (unregistered, unique) one is found.  Now we can register the same repository multiple times and the DOI doesn't rely on the name of the repository, which would cause issues when repositories were renamed or deleted.
> Generate new DOIs randomly

- cmd/gindoid/util.go
- templates/info.go
Instead of just DOI:<DOI> with link.
Assumes the URL exists in the reference description in the XML in parentheses, which is how we modified the current references to be.
Counterpart to g-node/libgin#22.
> Add full https://doi.org/<DOI> URL in references

- .gitignore
- Makefile
- cmd/gindoid/util.go
- templates/info.go
When a repository is registered multiple times, we indicate the relation between older and newer versions using related identifiers with types "IsOldVersionOf" and "IsNewVersionOf" appropriately.  We now use that information to add a notice to the landing page of an older dataset that links to the newer one.  On the landing page of the newer dataset, a less visible link to the older version is added as well.
Closes #57.
Example of an old version
Example of a new version
> Links to older and newer versions of the same base dataset

- templates/reqpage.go
On the request preparation page, include a warning about content licensed under different terms, specifically mentioning code.
It's not the most visible warning, but it might help.  It's not a very common case either, so I think it wouldn't be appropriate to add a bigger notice.
> Add notice about content licensed under different terms

- Dockerfile
- cmd/gindoid/config.go
- cmd/gindoid/dataset.go
- cmd/gindoid/dataset_test.go
- cmd/gindoid/util.go
- cmd/gindoid/util_test.go
- docker_startup.sh
- go.mod
- go.sum
This PR introduces the following major and minor changes:
- the DOI preparation server now clones the request GIN repository to a directory different from the hosting directory. This directory can be defined via the `doienv` environmental variables config file. The specific variable name is `preparation`.
- the zip functionality now actively excludes the `.git` folder from the zip file. The `derepoCloneDir` function has been removed from the registration procedure. This leaves the cloned repository intact in the `preparation` directory on the host machine and can be used for manual registration steps e.g. upload of annexed data to the DOI fork of the repository.
- the `Dockerfile` also supports the newly introduced `preparation` folder.
The removal of the `derepoCloneDir` resolves the …
> App freeze fix, zip changes and assets mapping

- cmd/gindoid/dataset.go
- cmd/gindoid/licenses.go
- cmd/gindoid/validation.go
- cmd/gindoid/validation_test.go
- go.mod
- go.sum
This PR adds code to check various aspects of provided license information when a DOI request is being processed. 
The license URL and license name provided via the datacite yaml file and the header line of the license file in the request repository are checked against a server internal common licenses struct array.
Warnings are issued, if any of the provided license URL, license name or header line cannot be identified as a common license and if URL, name and header do not appear to refer to one and the same license. This closes issue #79.
Since the full license text comparison and registration fail on minor license text differences is too strict and is therefore removed. This closes issue #87.
The PR also adds tests for all added functions.
> License checks

- README.md
- cmd/gindoid/dataset.go
- cmd/gindoid/licenses.go
- cmd/gindoid/messages.go
- cmd/gindoid/util.go
- cmd/gindoid/util_test.go
- cmd/gindoid/validation.go
- cmd/gindoid/validation_test.go
- go.mod
- go.sum
This PR adds additional admin warnings when processing a DOI request. Some of these changes require [changes in the libgin library merged into master](https://github.com/G-Node/libgin/pull/29).
- admin warnings are added if a reftype other than `isSupplementTo` is used. Closes #73.
- a warning is added, if the ID type of a reference is not available. Changes in libgin now exclude such entries from the XML file and the warning points this out to the admin. Closes #76.
- warnings are added, if an authorID has duplicate entries, if the authorID type cannot be identified, or if the ID type is known, but the ID value is missing. Changes in libgin now exclude authorID entries that only provide the ID type but not the ID value. Closes #77.
- a warning is added, if the `resourceType` is not …
> Additional admin warnings

- .github/workflows/run-tests.yml
- cmd/gindoid/config.go
- cmd/gindoid/dataset.go
- cmd/gindoid/dataset_test.go
- cmd/gindoid/genhtml.go
- cmd/gindoid/keywords.go
- cmd/gindoid/licenses.go
- cmd/gindoid/mail.go
- cmd/gindoid/main.go
- cmd/gindoid/templaterender_test.go
- cmd/gindoid/util.go
- cmd/gindoid/util_test.go
- cmd/gindoid/validation.go
- cmd/gindoid/validation_test.go
- cmd/gindoid/web.go
- cmd/gindoid/web_test.go
- cmd/gindoid/workdispatcher.go
- templates/common.go
- templates/keyword.go
- templates/kwindex.go
This PR removes all reported code issues by `go lint` `staticcheck` and `errcheck` and updates the github actions file to now fail on reported issues from `go lint`  and `staticcheck`.
The following constants, functions or methods are removed since they are no longer used:
- `genhtml.go`: `const defginurl`, `const defdoibase`, `const defstoreurl`, `func fetchAndParse`
- `util.go`: `func readBody`, `func makeUUID`
- `workerdispatcher.go`: method `Worker.stop`
The following functions have been moved to `util.go` since they were used by other package files as well:
- `genhtml.go`: `readFileAtPath`, `isURL`
- `dataset.go`: `readFileAtURL`
The following tests have been added:
- util.isURL test
- util.readFileAtPath test
- util.readFileAtURL test
> Code cleanup

- cmd/gindoid/genxml.go
- cmd/gindoid/main.go
- go.mod
- go.sum
Analogous to the `make-html` command line option of the gindoid binary, this PR adds the `make-doi-xml` command line option.
When provided a datacite.yml file, a URL to a datacite.yaml file or a public GIN repository containing a valid datacite.yaml file in the format `GIN:owner/repo`  the binary will create corresponding `doi.xml` files.
e.g. `./gindoid make-doi-xml GIN:jgrewe/grewe_etal_synchrony local_datacite.yml https://gin.g-node.org/jgrewe/grewe_etal_synchrony/raw/master/doi_info.xml`
> Command line tool to generate doi.xml files

- .gitignore
- cmd/gindoid/dataset.go
- cmd/gindoid/dataset_test.go
- cmd/gindoid/genxml.go
- cmd/gindoid/messages.go
- cmd/gindoid/templaterender_test.go
- cmd/gindoid/util.go
- cmd/gindoid/validation.go
- templates/reqfail.go
- templates/reqpage.go
This pull request
- changes the pre-registration check workflow to collect and display as many request breaking issues as possible. Now there are only three possible fails that are displayed to the user: (Closes issues #96, #101)
- if the datacite file is missing
- if the datacite file is not a valid yaml file and cannot be read
- if the datacite file contains any formal issues: missing values and invalid key entries are now collected and displayed together instead of in individual steps
- in addition the existence of a license file is always checked and displayed together with other issues to reduce the number of registration fails for a user.
- displays a warning that content linked via git submodules is not included in a published data set. Closes #93.
- adds a secondary round of annex …
> Secondary content download, change precheck workflow and git submodule warning

- .github/workflows/run-tests.yml
- cmd/gindoid/dataset.go
- cmd/gindoid/mail.go
- cmd/gindoid/validation.go
- cmd/gindoid/validation_test.go
- cmd/gindoid/web.go
This PR fixes some issues and adds the following updates:
- directory switching for cloning and zip creation has been refactored: now the server always switches back to the root directory after cloning or zip creation. This should fix #104.
- a notification email is sent to the server admins when the clone and zip process has successfully finished and no metadata issues have been identified. This closes #106.
- the metadata warning list to the server admins has been expanded. It now contains a warning, 
- if the repository contains submodules; this closes #92
- if an author ID cannot be verified with the corresponding ID service (orcid or researchID); this includes the datacite.yml author ID  template entries; this closes #107.
- when creating the initial DOI request issue on gin and …
> Fixes and updates

- cmd/gindoid/genindex.go
- cmd/gindoid/genindex_test.go
- cmd/gindoid/main.go
- cmd/gindoid/util.go
- templates/common.go
- templates/index.go
This PR adds the command line option `make-index` to generate the dataset listing page file as 'index.html' from one or more DataCite XML files.
Closes #48.
> Create dataset listing page

- cmd/gindoid/genall.go
- cmd/gindoid/gensitemap.go
- cmd/gindoid/gensitemap_test.go
- cmd/gindoid/keywords.go
- cmd/gindoid/main.go
This PR adds two command line options to the server executable
- `make-sitemap` generates the `urls.txt` google sitemap file from one or more DataCite XML files. Closes #109.
- `make-all` generates all html files (dataset listing page, keywords pages, landing pages) and the google sitemap file from one or more DataCite XML files. Closes #110 and #111.
> "Generate URLs" and "Generate all" CLI options
